In [1]:
import pandas as pd


In [2]:
train_data = pd.read_csv('C:\\Users\\VIKHYAT\\Downloads\\train.csv')
train_data

PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
0        0001_01     Europa     False     B/0/P    TRAPPIST-1e  39.0  False   
1        0002_01      Earth     False     F/0/S    TRAPPIST-1e  24.0  False   
2        0003_01     Europa     False     A/0/S    TRAPPIST-1e  58.0   True   
3        0003_02     Europa     False     A/0/S    TRAPPIST-1e  33.0  False   
4        0004_01      Earth     False     F/1/S    TRAPPIST-1e  16.0  False   
...          ...        ...       ...       ...            ...   ...    ...   
8688     9276_01     Europa     False    A/98/P    55 Cancri e  41.0   True   
8689     9278_01      Earth      True  G/1499/S  PSO J318.5-22  18.0  False   
8690     9279_01      Earth     False  G/1500/S    TRAPPIST-1e  26.0  False   
8691     9280_01     Europa     False   E/608/S    55 Cancri e  32.0  False   
8692     9280_02     Europa     False   E/608/S    TRAPPIST-1e  44.0  False   

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0             0.0        0.0           0.0     0.0     0.0    Maham Ofracculy   
1           109.0        9.0          25.0   549.0    44.0       Juanna Vines   
2            43.0     3576.0           0.0  6715.0    49.0      Altark Susent   
3             0.0     1283.0         371.0  3329.0   193.0       Solam Susent   
4           303.0       70.0         151.0   565.0     2.0  Willy Santantines   
...           ...        ...           ...     ...     ...                ...   
8688          0.0     6819.0           0.0  1643.0    74.0  Gravior Noxnuther   
8689          0.0        0.0           0.0     0.0     0.0    Kurta Mondalley   
8690          0.0        0.0        1872.0     1.0     0.0       Fayey Connon   
8691          0.0     1049.0           0.0   353.0  3235.0   Celeon Hontichre   
8692        126.0     4688.0           0.0     0.0    12.0   Propsh Hontichre   

      Transported  
0           False  
1            True  
2           False  
3           False  
4            True  
...           ...  
8688        False  
8689        False  
8690         True  
8691        False  
8692         True  

[8693 rows x 14 columns]

In [3]:
train_data.drop(['Name'] , inplace=True ,  axis=1)
train_data

PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
0        0001_01     Europa     False     B/0/P    TRAPPIST-1e  39.0  False   
1        0002_01      Earth     False     F/0/S    TRAPPIST-1e  24.0  False   
2        0003_01     Europa     False     A/0/S    TRAPPIST-1e  58.0   True   
3        0003_02     Europa     False     A/0/S    TRAPPIST-1e  33.0  False   
4        0004_01      Earth     False     F/1/S    TRAPPIST-1e  16.0  False   
...          ...        ...       ...       ...            ...   ...    ...   
8688     9276_01     Europa     False    A/98/P    55 Cancri e  41.0   True   
8689     9278_01      Earth      True  G/1499/S  PSO J318.5-22  18.0  False   
8690     9279_01      Earth     False  G/1500/S    TRAPPIST-1e  26.0  False   
8691     9280_01     Europa     False   E/608/S    55 Cancri e  32.0  False   
8692     9280_02     Europa     False   E/608/S    TRAPPIST-1e  44.0  False   

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck  Transported  
0             0.0        0.0           0.0     0.0     0.0        False  
1           109.0        9.0          25.0   549.0    44.0         True  
2            43.0     3576.0           0.0  6715.0    49.0        False  
3             0.0     1283.0         371.0  3329.0   193.0        False  
4           303.0       70.0         151.0   565.0     2.0         True  
...           ...        ...           ...     ...     ...          ...  
8688          0.0     6819.0           0.0  1643.0    74.0        False  
8689          0.0        0.0           0.0     0.0     0.0        False  
8690          0.0        0.0        1872.0     1.0     0.0         True  
8691          0.0     1049.0           0.0   353.0  3235.0        False  
8692        126.0     4688.0           0.0     0.0    12.0         True  

[8693 rows x 13 columns]

In [4]:
train_data['HomePlanet'].unique()

array(['Europa', 'Earth', 'Mars', nan], dtype=object)

In [5]:
train_data['HomePlanet'].fillna('NULL' , inplace=True)
train_data['HomePlanet'].unique()

array(['Europa', 'Earth', 'Mars', 'NULL'], dtype=object)

In [6]:
train_data['HomePlanet'].replace(['Europa', 'Earth', 'Mars', 'NULL'] , [1,2,3,4] , inplace=True)
train_data['HomePlanet'].unique()

array([1, 2, 3, 4], dtype=int64)

In [7]:
train_data.isnull().sum()

PassengerId       0
HomePlanet        0
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Transported       0
dtype: int64

In [8]:
train_data['CryoSleep'].unique()

array([False, True, nan], dtype=object)

In [9]:
train_data['RoomService'].fillna(0 , inplace=True)
train_data['FoodCourt'].fillna(0 , inplace=True)
train_data['ShoppingMall'].fillna(0 , inplace=True)
train_data.isnull().sum()

PassengerId       0
HomePlanet        0
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService       0
FoodCourt         0
ShoppingMall      0
Spa             183
VRDeck          188
Transported       0
dtype: int64

In [10]:
train_data['Spa'].fillna(0 , inplace=True)
train_data['VRDeck'].fillna(0 , inplace=True)
train_data.isnull().sum()

PassengerId       0
HomePlanet        0
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService       0
FoodCourt         0
ShoppingMall      0
Spa               0
VRDeck            0
Transported       0
dtype: int64

In [11]:
train_data['Age'].mean()

28.82793046746535

In [12]:
train_data['Age'].fillna(28.82793046746535 , inplace=True)
train_data.isnull().sum()

PassengerId       0
HomePlanet        0
CryoSleep       217
Cabin           199
Destination     182
Age               0
VIP             203
RoomService       0
FoodCourt         0
ShoppingMall      0
Spa               0
VRDeck            0
Transported       0
dtype: int64

In [13]:
train_data['VIP'].unique()

array([False, True, nan], dtype=object)

In [14]:
train_data['VIP'].value_counts()

False    8291
True      199
Name: VIP, dtype: int64

In [15]:
train_data['VIP'].fillna('NULL' , inplace=True)

In [16]:
train_data['VIP'].drop(train_data.index[train_data['VIP']=='NULL'] ,axis=0, inplace=True)

In [17]:
train_data['VIP'].unique()

array([False, True, 'NULL'], dtype=object)

In [18]:
train_data.isnull().sum()

PassengerId       0
HomePlanet        0
CryoSleep       217
Cabin           199
Destination     182
Age               0
VIP               0
RoomService       0
FoodCourt         0
ShoppingMall      0
Spa               0
VRDeck            0
Transported       0
dtype: int64

In [19]:
train_data['VIP'].replace([False, True, 'NULL'] , [-1 , 1, 0] , inplace=True)
train_data['VIP'].unique()

array([-1,  1,  0], dtype=int64)

In [20]:
train_data['CryoSleep'].unique()

array([False, True, nan], dtype=object)

In [21]:
train_data['CryoSleep'].fillna('NULL' ,inplace=True)
train_data['CryoSleep'].replace([False , True , 'NULL'] , [-1,1,0] , inplace=True)
train_data['CryoSleep'].unique()

array([-1,  1,  0], dtype=int64)

In [22]:
train_data

PassengerId  HomePlanet  CryoSleep     Cabin    Destination   Age  VIP  \
0        0001_01           1         -1     B/0/P    TRAPPIST-1e  39.0   -1   
1        0002_01           2         -1     F/0/S    TRAPPIST-1e  24.0   -1   
2        0003_01           1         -1     A/0/S    TRAPPIST-1e  58.0    1   
3        0003_02           1         -1     A/0/S    TRAPPIST-1e  33.0   -1   
4        0004_01           2         -1     F/1/S    TRAPPIST-1e  16.0   -1   
...          ...         ...        ...       ...            ...   ...  ...   
8688     9276_01           1         -1    A/98/P    55 Cancri e  41.0    1   
8689     9278_01           2          1  G/1499/S  PSO J318.5-22  18.0   -1   
8690     9279_01           2         -1  G/1500/S    TRAPPIST-1e  26.0   -1   
8691     9280_01           1         -1   E/608/S    55 Cancri e  32.0   -1   
8692     9280_02           1         -1   E/608/S    TRAPPIST-1e  44.0   -1   

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck  Transported  
0             0.0        0.0           0.0     0.0     0.0        False  
1           109.0        9.0          25.0   549.0    44.0         True  
2            43.0     3576.0           0.0  6715.0    49.0        False  
3             0.0     1283.0         371.0  3329.0   193.0        False  
4           303.0       70.0         151.0   565.0     2.0         True  
...           ...        ...           ...     ...     ...          ...  
8688          0.0     6819.0           0.0  1643.0    74.0        False  
8689          0.0        0.0           0.0     0.0     0.0        False  
8690          0.0        0.0        1872.0     1.0     0.0         True  
8691          0.0     1049.0           0.0   353.0  3235.0        False  
8692        126.0     4688.0           0.0     0.0    12.0         True  

[8693 rows x 13 columns]

In [23]:
train_data['Cabin'].unique()

array(['B/0/P', 'F/0/S', 'A/0/S', ..., 'G/1499/S', 'G/1500/S', 'E/608/S'],
      dtype=object)

In [24]:
train_data['Destination'].unique()

array(['TRAPPIST-1e', 'PSO J318.5-22', '55 Cancri e', nan], dtype=object)

In [25]:
train_data['Destination'].fillna('NULL' , inplace=True)
train_data['Destination'].replace(['TRAPPIST-1e', 'PSO J318.5-22', '55 Cancri e', 'NULL'] , [1,2,3,4] , inplace=True)
train_data['Destination'].unique()

array([1, 2, 3, 4], dtype=int64)

In [26]:
len(train_data['Cabin'].unique())

6561

In [27]:
train_data.drop(['Cabin'] , inplace=True , axis=1)
train_data

PassengerId  HomePlanet  CryoSleep  Destination   Age  VIP  RoomService  \
0        0001_01           1         -1            1  39.0   -1          0.0   
1        0002_01           2         -1            1  24.0   -1        109.0   
2        0003_01           1         -1            1  58.0    1         43.0   
3        0003_02           1         -1            1  33.0   -1          0.0   
4        0004_01           2         -1            1  16.0   -1        303.0   
...          ...         ...        ...          ...   ...  ...          ...   
8688     9276_01           1         -1            3  41.0    1          0.0   
8689     9278_01           2          1            2  18.0   -1          0.0   
8690     9279_01           2         -1            1  26.0   -1          0.0   
8691     9280_01           1         -1            3  32.0   -1          0.0   
8692     9280_02           1         -1            1  44.0   -1        126.0   

      FoodCourt  ShoppingMall     Spa  VRDeck  Transported  
0           0.0           0.0     0.0     0.0        False  
1           9.0          25.0   549.0    44.0         True  
2        3576.0           0.0  6715.0    49.0        False  
3        1283.0         371.0  3329.0   193.0        False  
4          70.0         151.0   565.0     2.0         True  
...         ...           ...     ...     ...          ...  
8688     6819.0           0.0  1643.0    74.0        False  
8689        0.0           0.0     0.0     0.0        False  
8690        0.0        1872.0     1.0     0.0         True  
8691     1049.0           0.0   353.0  3235.0        False  
8692     4688.0           0.0     0.0    12.0         True  

[8693 rows x 12 columns]

In [28]:
import tensorflow as tf
import numpy as np

In [29]:
train_ans = train_data['Transported']

In [30]:
train_ans

0       False
1        True
2       False
3       False
4        True
        ...  
8688    False
8689    False
8690     True
8691    False
8692     True
Name: Transported, Length: 8693, dtype: bool

In [31]:
type(train_ans)

pandas.core.series.Series

In [32]:
train_ans = train_ans.to_frame()

In [33]:
train_data.drop(['VIP'] ,axis=1 , inplace=True)
train_data

PassengerId  HomePlanet  CryoSleep  Destination   Age  RoomService  \
0        0001_01           1         -1            1  39.0          0.0   
1        0002_01           2         -1            1  24.0        109.0   
2        0003_01           1         -1            1  58.0         43.0   
3        0003_02           1         -1            1  33.0          0.0   
4        0004_01           2         -1            1  16.0        303.0   
...          ...         ...        ...          ...   ...          ...   
8688     9276_01           1         -1            3  41.0          0.0   
8689     9278_01           2          1            2  18.0          0.0   
8690     9279_01           2         -1            1  26.0          0.0   
8691     9280_01           1         -1            3  32.0          0.0   
8692     9280_02           1         -1            1  44.0        126.0   

      FoodCourt  ShoppingMall     Spa  VRDeck  Transported  
0           0.0           0.0     0.0     0.0        False  
1           9.0          25.0   549.0    44.0         True  
2        3576.0           0.0  6715.0    49.0        False  
3        1283.0         371.0  3329.0   193.0        False  
4          70.0         151.0   565.0     2.0         True  
...         ...           ...     ...     ...          ...  
8688     6819.0           0.0  1643.0    74.0        False  
8689        0.0           0.0     0.0     0.0        False  
8690        0.0        1872.0     1.0     0.0         True  
8691     1049.0           0.0   353.0  3235.0        False  
8692     4688.0           0.0     0.0    12.0         True  

[8693 rows x 11 columns]

In [34]:
train_ans['Transported'].replace([False , True] , [0,1] , inplace=True)
train_ans

Transported
0               0
1               1
2               0
3               0
4               1
...           ...
8688            0
8689            0
8690            1
8691            0
8692            1

[8693 rows x 1 columns]

In [35]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()

In [36]:
clf.fit(train_data, train_ans)

D:\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression()

In [37]:
clf.score(train_data , train_ans)

0.7789025652824111

In [38]:
test_data = pd.read_csv('C:\\Users\\VIKHYAT\\Downloads\\test.csv')
test_data

PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
0        0013_01      Earth      True     G/3/S    TRAPPIST-1e  27.0  False   
1        0018_01      Earth     False     F/4/S    TRAPPIST-1e  19.0  False   
2        0019_01     Europa      True     C/0/S    55 Cancri e  31.0  False   
3        0021_01     Europa     False     C/1/S    TRAPPIST-1e  38.0  False   
4        0023_01      Earth     False     F/5/S    TRAPPIST-1e  20.0  False   
...          ...        ...       ...       ...            ...   ...    ...   
4272     9266_02      Earth      True  G/1496/S    TRAPPIST-1e  34.0  False   
4273     9269_01      Earth     False       NaN    TRAPPIST-1e  42.0  False   
4274     9271_01       Mars      True   D/296/P    55 Cancri e   NaN  False   
4275     9273_01     Europa     False   D/297/P            NaN   NaN  False   
4276     9277_01      Earth      True  G/1498/S  PSO J318.5-22  43.0  False   

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck              Name  
0             0.0        0.0           0.0     0.0     0.0   Nelly Carsoning  
1             0.0        9.0           0.0  2823.0     0.0    Lerome Peckers  
2             0.0        0.0           0.0     0.0     0.0   Sabih Unhearfus  
3             0.0     6652.0           0.0   181.0   585.0  Meratz Caltilter  
4            10.0        0.0         635.0     0.0     0.0   Brence Harperez  
...           ...        ...           ...     ...     ...               ...  
4272          0.0        0.0           0.0     0.0     0.0       Jeron Peter  
4273          0.0      847.0          17.0    10.0   144.0     Matty Scheron  
4274          0.0        0.0           0.0     0.0     0.0       Jayrin Pore  
4275          0.0     2680.0           0.0     0.0   523.0    Kitakan Conale  
4276          0.0        0.0           0.0     0.0     0.0  Lilace Leonzaley  

[4277 rows x 13 columns]

In [39]:
test_data.drop(['Name'] , inplace=True ,  axis=1)
test_data['HomePlanet'].fillna('NULL' , inplace=True)
test_data['HomePlanet'].replace(['Europa', 'Earth', 'Mars', 'NULL'] , [1,2,3,4] , inplace=True)
test_data['RoomService'].fillna(0 , inplace=True)
test_data['FoodCourt'].fillna(0 , inplace=True)
test_data['ShoppingMall'].fillna(0 , inplace=True)
test_data['Spa'].fillna(0 , inplace=True)
test_data['VRDeck'].fillna(0 , inplace=True)
me = test_data['Age'].mean()
test_data['Age'].fillna(me , inplace=True)
test_data['VIP'].fillna('NULL' , inplace=True)
test_data['VIP'].replace([False, True, 'NULL'] , [-1 , 1, 0] , inplace=True)
test_data['CryoSleep'].fillna('NULL' ,inplace=True)
test_data['CryoSleep'].replace([False , True , 'NULL'] , [-1,1,0] , inplace=True)
test_data['Destination'].fillna('NULL' , inplace=True)
test_data['Destination'].replace(['TRAPPIST-1e', 'PSO J318.5-22', '55 Cancri e', 'NULL'] , [1,2,3,4] , inplace=True)
test_data.drop(['Cabin'] , inplace=True , axis=1)
test_data

PassengerId  HomePlanet  CryoSleep  Destination        Age  VIP  \
0        0013_01           2          1            1  27.000000   -1   
1        0018_01           2         -1            1  19.000000   -1   
2        0019_01           1          1            3  31.000000   -1   
3        0021_01           1         -1            1  38.000000   -1   
4        0023_01           2         -1            1  20.000000   -1   
...          ...         ...        ...          ...        ...  ...   
4272     9266_02           2          1            1  34.000000   -1   
4273     9269_01           2         -1            1  42.000000   -1   
4274     9271_01           3          1            3  28.658146   -1   
4275     9273_01           1         -1            4  28.658146   -1   
4276     9277_01           2          1            2  43.000000   -1   

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck  
0             0.0        0.0           0.0     0.0     0.0  
1             0.0        9.0           0.0  2823.0     0.0  
2             0.0        0.0           0.0     0.0     0.0  
3             0.0     6652.0           0.0   181.0   585.0  
4            10.0        0.0         635.0     0.0     0.0  
...           ...        ...           ...     ...     ...  
4272          0.0        0.0           0.0     0.0     0.0  
4273          0.0      847.0          17.0    10.0   144.0  
4274          0.0        0.0           0.0     0.0     0.0  
4275          0.0     2680.0           0.0     0.0   523.0  
4276          0.0        0.0           0.0     0.0     0.0  

[4277 rows x 11 columns]

In [40]:
predicted = clf.predict(test_data)

In [41]:
predicted

array([1, 0, 1, ..., 1, 1, 1], dtype=int64)

In [42]:
sub = test_data['PassengerId']
sub

0       0013_01
1       0018_01
2       0019_01
3       0021_01
4       0023_01
         ...   
4272    9266_02
4273    9269_01
4274    9271_01
4275    9273_01
4276    9277_01
Name: PassengerId, Length: 4277, dtype: object

In [43]:
sub = sub.to_frame()

In [44]:
sub

PassengerId
0        0013_01
1        0018_01
2        0019_01
3        0021_01
4        0023_01
...          ...
4272     9266_02
4273     9269_01
4274     9271_01
4275     9273_01
4276     9277_01

[4277 rows x 1 columns]

In [45]:
predict = pd.DataFrame(predicted , columns = ['Predict'])
predict

Predict
0           1
1           0
2           1
3           1
4           0
...       ...
4272        1
4273        1
4274        1
4275        1
4276        1

[4277 rows x 1 columns]

In [47]:
sub['Transported'] = predict['Predict']
sub

PassengerId  Transported
0        0013_01            1
1        0018_01            0
2        0019_01            1
3        0021_01            1
4        0023_01            0
...          ...          ...
4272     9266_02            1
4273     9269_01            1
4274     9271_01            1
4275     9273_01            1
4276     9277_01            1

[4277 rows x 2 columns]

In [48]:
sub['Transported'].replace([0 , 1] , [False , True] , inplace=True)
sub

PassengerId  Transported
0        0013_01         True
1        0018_01        False
2        0019_01         True
3        0021_01         True
4        0023_01        False
...          ...          ...
4272     9266_02         True
4273     9269_01         True
4274     9271_01         True
4275     9273_01         True
4276     9277_01         True

[4277 rows x 2 columns]

In [49]:
sub.to_csv('C:\\Users\\VIKHYAT\\Downloads\\submission.csv' , index=False)

In [50]:
test_data.isnull().sum()

PassengerId     0
HomePlanet      0
CryoSleep       0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
dtype: int64